### ISSUE TITLE
Few nodes' icons missing

### ISSUE THREAD

**Issue by bojidar-bg** [djrm/godot-design#1]
Currently, some nodes are missing their icons. Here is a list, ordered by "relative importance"

| Group | Nodes |
| ----- | ----- |
| Classes that can be created | `Tween`, `CanvasLayer`, `ParallaxBackground`, `ParllaxLayer`, `Tabs`, `ViewportSprite`, `InverseKinematics`, `PanelContainer` |
| Used mostly in editor context | `GraphEdit`, `GraphNode`, `EditorPlugin` |
| Base classes that can be created | `Container`, `Range` |
| Base classes that have many inherited classes, but can't exist on their own | `BaseButton`, `Seperator`, `ButtonArray`, `CollisionObject{,2D}`, `PhysicsBody{,2D}`, `SoundPlayer2D`, `SpatialPlayer`, `Joint{,2D}`, `VisualInstance`, `GeometryInstance`, `Light`, `BoxContainer`, `SplitContainer` |

Also, great work! :+1:

**Comment by bojidar-bg** [comment]
Suggestions for the some of the icons:
* `Tween` - Something to represent a transition from A to B. Maybe have a triangle, a square, and an arrow that points from one to the other.. if space allows, I mean :smile:
* `CanvasLayer` - Probably the `CanvasItem` icon boxed, or maybe a box with some mountains on it.
* `ParallaxBackground` - Multiple `CanvasLayer` icons layered at different scales and positions. Maybe multiple mountains behind each other, inside a box.
* `ParllaxLayer` - Same as in `ParallaxBackground`, but without the box around.
* `ViewportSprite` - `Viewport`'s icon with a blue color and something inside probably.

**Comment by djrm** [comment]
will check that out

**Comment by djrm** [comment]
Maybe the abstract classes should not have icons, in that way they look like headers in the node palette

**Comment by bojidar-bg** [comment]
@djrm Agreed, that sounds like a nice idea. I mentioned them just in case ^^

**Comment by djrm** [comment]
Fixed with 1cbb44edf67f9bb0352d9bd7d72a694e17ee4a08
