### ISSUE TITLE
feedback on the new icons

### ISSUE THREAD

**Issue by nunodonato** [djrm/godot-design#2]
Hi folks :)

just compiled godot from git and love the new icons!
I have 2 suggestions where I think it needs improvement

1 - the save icon in the inspector (as when you are saving a resource). it doesnt look like a save icon, its more similar to the lock icon of the 2d editor. 
2 - in the file browser, the folder icon and the plain file icon are too similar, when I open a folder full of files, its very confusing to understand what is what. Would be great if the folder icon could be less square-ish, or perhaps with a yellow color (like a manila folder?)

love everything else, great job!! :D

**Comment by djrm** [comment]
@nunodonato The colored folders, seems to be a good idea, The save icon, looks good to me (Theres no much space to make something more detailed), but maybe is my particular case, maybe you could post a screenshot showing how it looks like in your configuration

**Comment by nunodonato** [comment]
![saveicon](https://cloud.githubusercontent.com/assets/1642015/15835693/fcfa5eae-2c28-11e6-8637-e537f5ce303a.png)

it doesnt look like a save to me, its very similar to the lock icon.

also, why are people still using floppy disks to represent save? most people nowadays never even saw a floppy disk :D

**Comment by djrm** [comment]
hehe yeah, (see you can tell its a floppy), but i cant put a hardrive or a SSD, nobody would understand it, i guess the floppy will be part of the icons for a long time, even when it lost a meaning as a device in the future, like it will be 'just the save icon'.

**Comment by nunodonato** [comment]
i know its a floppy because its what it used to be, and because I have SEEN a floppy :p

**Comment by nunodonato** [comment]
found this too
![save](https://cloud.githubusercontent.com/assets/1642015/15836088/0cb62808-2c2b-11e6-8740-5046ee891df7.png)

**Comment by djrm** [comment]
dont know, the new icons doesn't seem to be a save icon, more like a download icon

**Comment by djrm** [comment]
what about this
![screenshot from 2016-06-06 15-12-10](https://cloud.githubusercontent.com/assets/1103897/15836152/168c31b0-2bf9-11e6-8d48-8e86e3decfec.png)

**Comment by nunodonato** [comment]
well, downloading *is* saving ;)

the last one is the best looking floppy of all the 3 :)

**Comment by djrm** [comment]
but saving a resource is not downloading, also the save buttons is used in other buttons

**Comment by JarLowrey** [comment]
Also, the debug icon in the top menu is confusing because 1) it is a "remote" icon and 2) it opens a menu instead of being a 1-click button - https://github.com/godotengine/godot/issues/8480#issuecomment-296222869
