### ISSUE TITLE
RatingStar and RatingNoStar are way too similar

### ISSUE THREAD

**Issue by bojidar-bg** [djrm/godot-design#4]
Here is a screen for completeness:
![image](https://cloud.githubusercontent.com/assets/5276727/16232191/3859285e-37d2-11e6-936c-c2a9487788fa.png)
Try guessing which of the two has more stars, the top one, or the bottom one ^^

**Comment by djrm** [comment]
This has been changed

**Comment by bojidar-bg** [comment]
Sorry, my bad..
